Add new page, change configs
KhaosResearch/SMARTFOOD pull request #3
Opened 2024-03-14 09:05 UTC by Juansanchezrodriguez1999

2024-03-19 07:24 UTC, benhid requested changes

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +def login_is_required_vre2(function):
¿Por qué está duplicado?

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +def home_VRE2():
¿`home_VRE2`?

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +def joystic():
Typo

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +        # CAMBIAR LOCALHOST
Comentario en español

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +        response = requests.post('http://localhost:9010/containers', headers={"X-Api-Key": "s3cr3t"})
Todo esto debe ir en .env

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +                redirect_url = f"http://{container_name}.gazebo.test"
Esto también deben poder cambiarlo;

```py
redirect_url_gazebo=`https://{container_name}.lifewatch.eu`

redirect_url_gazebo.format(container_name=container_name)
```

2024-03-19 07:24 UTC, benhid commented on Webpage/main.py
> +                return "No se pudo obtener el nombre del contenedor", 500
Español

2024-03-19 08:13 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +def login_is_required_vre2(function):
Intenté usar la misma función pero daba error al estar wrapper duplicado. Al ser decorador y envolver a la funcion no actua como una funcion de python al uso

2024-03-19 08:14 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +def home_VRE2():
Es el nombre que me dijeron para la pagina por eso llamé así la funcion

2024-03-19 08:15 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +def joystic():
joysticK arreglado

2024-03-19 08:15 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +        # CAMBIAR LOCALHOST
Eliminados, lo he metido en el .env

2024-03-19 08:15 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +        response = requests.post('http://localhost:9010/containers', headers={"X-Api-Key": "s3cr3t"})
metido tambien en el .env

2024-03-19 08:15 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +                redirect_url = f"http://{container_name}.gazebo.test"
metidoo en .env

2024-03-19 08:16 UTC, Juansanchezrodriguez1999 commented on Webpage/main.py
> +                return "No se pudo obtener el nombre del contenedor", 500
cambiado

2024-03-20 09:35 UTC, AmbroxMr commented
LGTM and @benhid gave thumbs up

2024-03-20 09:37 UTC, merged